language: ruby
rvm: 2.4
addons:
  apt:
    packages:
      - libcurl4-openssl-dev # required to avoid SSL errors

before_install:
 - export NOKOGIRI_USE_SYSTEM_LIBRARIES=true
install: gem install jekyll html-proofer

script: ./test.sh

sudo: false
