language: ruby
rvm: 2.4
addons:
  apt:
    packages:
      - libcurl4-openssl-dev # required to avoid SSL errors
install: gem install jekyll html-proofer
script: test.sh
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false
