language: ruby
rvm: 2.4
install: gem install jekyll html-proofer
script: jekyll build && htmlproofer --check-html --check-favicon --check-opengraph --url-ignore 'https://scholar.google.com/citations?user=OqC2Vc8AAAAJ&hl=en' --empty-alt-ignore _site
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
sudo: false
