  # Site settings
title: Shane M. Parker
email: smparker@uci.edu
description: > # this means to ignore newlines until "baseurl:"
  Software developed by a quantum chemist.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://smparker.github.io" # the base hostname & protocol for your site
#twitter_username: sparkadocious
github_username:  smparker
google_scholar: smparker

# Build settings
markdown: kramdown

exclude: [ latex_cv, launch ]

# Collections
collections:
  notes:
    output: true
    defaults:
      scope:
        path = ""
        type = notes
      values:
        layout = page
