  # Site settings
title: Parker Group
email: shane.parker@case.edu
description: > # this means to ignore newlines until "baseurl:"
  The Parker Group: Computational Photochemistry
baseurl: "" # the subpath of your site, e.g. /blog/
motto: High Performance Computational Photochemistry
cv:
  name: smp-cv.pdf
  date: "11/04/2020"
url: "https://quantumparker.com" # the base hostname & protocol for your site
#twitter_username: sparkadocious
github_username:  smparker
google_scholar: smparker
sass:
  sass_dir: _sass
  style: compress

# Build settings
markdown: kramdown
mathjax: true

exclude: [ latex_cv, launch, Gemfile, Rakefile ]

# Collections
collections:
  notes:
    output: true
    defaults:
      scope:
        path: ""
        type: notes
      values:
        layout: page
  collab:
    output: false
    permalink: /:collection/:path/
    defaults:
      scope:
        path: ""
        type: collab
      values:
        layout: page
