#!/bin/bash


if [ "$1" != "" ]; then
  name="$1"
else
  name="smparker_cv_$(date "+%Y_%m_%d")"
fi

printf "%-80s\r" "Building CV: generating"
./make_tex_cv.py -p -s -S all -t cv --cwru > $name.tex

for pass in "first" "second"; do
  printf "%-80s\r" "Building ${x}: $pass pass"
  xelatex -interaction=nonstopmode $name.tex | grep "Error"
done

for x in ${name}.{aux,log,out}; do
  rm $x
done

printf "%-80s\r" ""
